### ISSUE TITLE
Modify the code where it could handle multiple expenses.

### ISSUE THREAD

**Issue by Free-Software-Sara** [Free-Software-Sara/Expense-Tracker#3]
Currently the app only takes single expense and then displays it in the chart.
Modify the code where multiple expenses are taken from the user and then create a bargraph accordingly

**Comment by spoorthyvv** [comment]
I would like to work in this issue

**Comment by Free-Software-Sara** [comment]
Assigning it to you

**Comment by VPeron** [comment]
Hey @Free-Software-Sara could I chip in too?

**Comment by Free-Software-Sara** [comment]
please do

**Comment by Free-Software-Sara** [comment]
i have assigned it to you.
kindly note it has been hosted in the streamlit cloud. Do check if the code is compatible accordingly .
